DE_PARA_OCORRENCIAS = {
    "1": {
        "descricao": "Criação da solicitação",
        "statusBadge": "CRIADA",
        "ultimoStatus": "Criação da solicitação",
    },
    "2": {
        "descricao": "Solicitação em Rota",
        "statusBadge": "EM ROTA",
        "ultimoStatus": "Solicitação em Rota",
    },
    "3": {
        "descricao": "Agendamento da Solicitação",
        "statusBadge": "AGENDADO",
        "ultimoStatus": "Agendamento da Solicitação",
    },
    "5": {
        "descricao": "Não Coletado",
        "statusBadge": "NÃO COLETADO",
        "ultimoStatus": "Não Coletado",
    },
    "6": {
        "descricao": "Coleta realizada",
        "statusBadge": "COLETADO",
        "ultimoStatus": "Coleta realizada",
    },
    "7": {
        "descricao": "Cancelamento de solicitação",
        "statusBadge": "CANCELADA",
        "ultimoStatus": "Cancelamento de solicitação",
    },
    "10": {
        "descricao": "Devolução Realizada",
        "statusBadge": "DEVOLVIDO",
        "ultimoStatus": "Devolução Realizada",
    },
    "11": {
        "descricao": "Não Devolvido",
        "statusBadge": "NÃO DEVOLVIDO",
        "ultimoStatus": "Não Devolvido",
    },
    "13": {
        "descricao": "Geração de lista de devolução",
        "statusBadge": "DEVOLUÇÃO EM ROTA",
        "ultimoStatus": "Geração de lista de devolução",
    },
    "14": {
        "descricao": "Envio de Transferência para devolução",
        "statusBadge": "EM TRANSFERÊNCIA DEVOLUÇÃO",
        "ultimoStatus": "Envio de Transferência para devolução",
    },
    "15": {
        "descricao": "Cancelamento romaneio de coleta",
        "statusBadge": "SEM MUDANÇA DE STATUS",
        "ultimoStatus": "Cancelamento romaneio de coleta",
    },
    "16": {
        "descricao": "Reagendamento da Solicitação",
        "statusBadge": "REAGENDADO",
        "ultimoStatus": "Reagendamento da Solicitação",
    },
    "17": {
        "descricao": "Recebimento de transferência entre unidades",
        "statusBadge": "TRANSFERÊNCIA ENTREGA RECEBIDA",
        "ultimoStatus": "Recebimento de transferência entre unidades",
    },
    "19": {
        "descricao": "Alteração de Status",
        "statusBadge": "SEM MUDANÇA DE STATUS",
        "ultimoStatus": "Alteração de Status",
    },
    "20": {
        "descricao": "Cancelamento Lista de Transferência",
        "statusBadge": "SEM MUDANÇA DE STATUS",
        "ultimoStatus": "Cancelamento Lista de Transferência",
    },
    "21": {
        "descricao": "Tentativa de Agendamento",
        "statusBadge": "AGENDADO",
        "ultimoStatus": "Tentativa de Agendamento",
    },
    "22": {
        "descricao": "Cancelamento romaneio de devolução",
        "statusBadge": "SEM MUDANÇA DE STATUS",
        "ultimoStatus": "Cancelamento romaneio de devolução",
    },
    "23": {
        "descricao": "Pendência de devolução resolvida",
        "statusBadge": "DEVOLUÇÃO",
        "ultimoStatus": "Pendência de devolução resolvida",
    },
    "24": {
        "descricao": "Arquivo Recebido",
        "statusBadge": "ARQUIVO RECEBIDO",
        "ultimoStatus": "Arquivo Recebido",
    },
    "25": {
        "descricao": "Coletado e recebido na base",
        "statusBadge": "RECEBIDO",
        "ultimoStatus": "Coletado e recebido na base",
    },
    "27": {
        "descricao": "Tratamento de Pendência",
        "statusBadge": "PENDENTE",
        "ultimoStatus": "Tratamento de Pendência",
    },
    "28": {
        "descricao": "Recebimento de volumes para entrega",
        "statusBadge": "RECEBIDO",
        "ultimoStatus": "Recebimento de volumes para entrega",
    },
    "29": {
        "descricao": "Volumes armazenados",
        "statusBadge": "ARMAZENADO",
        "ultimoStatus": "Volumes armazenados",
    },
    "30": {
        "descricao": "Picking realizado",
        "statusBadge": "PROCESSADO",
        "ultimoStatus": "Picking realizado",
    },
    "31": {
        "descricao": "Entrega Realizada",
        "statusBadge": "ENTREGUE",
        "ultimoStatus": "Entrega Realizada",
    },
    "32": {
        "descricao": "Entrega não Realizada",
        "statusBadge": "PENDENTE",
        "ultimoStatus": "Entrega não Realizada",
    },
    "33": {
        "descricao": "Remessa rejeitada na criação",
        "statusBadge": "REJEITADO",
        "ultimoStatus": "Remessa rejeitada na criação",
    },
    "34": {
        "descricao": "Cancelamento de romaneio de entrega",
        "statusBadge": "SEM MUDANÇA DE STATUS",
        "ultimoStatus": "Cancelamento de romaneio de entrega",
    },
    "35": {
        "descricao": "Transferência de volumes para entrega",
        "statusBadge": "EM TRANSFERÊNCIA ENTREGA",
        "ultimoStatus": "Transferência de volumes para entrega",
    },
    "36": {
        "descricao": "Tratamento de Pendência (Devolver)",
        "statusBadge": "CUSTODIA",
        "ultimoStatus": "Tratamento de Pendência (Devolver)",
    },
    "37": {
        "descricao": "Tratamento de Pendência (Reentregar)",
        "statusBadge": "CUSTODIA",
        "ultimoStatus": "Tratamento de Pendência (Reentregar)",
    },
    "39": {
        "descricao": "Baixa em indenização",
        "statusBadge": "INDENIZAÇÃO",
        "ultimoStatus": "Baixa em indenização",
    },
    "40": {
        "descricao": "Solicitação removida do romaneio",
        "statusBadge": "AGENDADO",
        "ultimoStatus": "Solicitação removida do romaneio",
    },
    "44": {
        "descricao": "Estorno de Solicitação",
        "statusBadge": "SEM MUDANÇA DE STATUS",
        "ultimoStatus": "Estorno de Solicitação",
    },
    "45": {
        "descricao": "Consolidação de Coletas",
        "statusBadge": "CONSOLIDADO",
        "ultimoStatus": "Consolidação de Coletas",
    },
    "46": {
        "descricao": "Averbação de Carga",
        "statusBadge": "SEM MUDANÇA DE STATUS",
        "ultimoStatus": "Averbação de Carga",
    },
    "47": {
        "descricao": "Cancelamento de Averbação de Carga",
        "statusBadge": "SEM MUDANÇA DE STATUS",
        "ultimoStatus": "Cancelamento de Averbação de Carga",
    },
    "48": {
        "descricao": "Tentativa de Averbação de Carga",
        "statusBadge": "SEM MUDANÇA DE STATUS",
        "ultimoStatus": "Tentativa de Averbação de Carga",
    },
    "49": {
        "descricao": "Entrega Realizada (Mobile)",
        "statusBadge": "ENTREGUE",
        "ultimoStatus": "Entrega Realizada (Mobile)",
    },
    "50": {
        "descricao": "Recebimento de Volumes da Entrega Cancelado",
        "statusBadge": "SEM MUDANÇA DE STATUS",
        "ultimoStatus": "Recebimento de Volumes da Entrega Cancelado",
    },
    "51": {
        "descricao": "Coleta de Carga no embarcador",
        "statusBadge": "COLETADO NO EMBARCADOR",
        "ultimoStatus": "Coleta de Carga no embarcador",
    },
    "52": {
        "descricao": "Volume não recebido",
        "statusBadge": "SEM MUDANÇA DE STATUS",
        "ultimoStatus": "Volume não recebido",
    },
    "53": {
        "descricao": "Solicitação enviada para indenização",
        "statusBadge": "INDENIZAÇÃO",
        "ultimoStatus": "Solicitação enviada para indenização",
    },
    "55": {
        "descricao": "Unidade de Coleta de Carga Alterada",
        "statusBadge": "SEM MUDANÇA DE STATUS",
        "ultimoStatus": "Unidade de Coleta de Carga Alterada",
    },
    "56": {
        "descricao": "Anulação de sinistro",
        "statusBadge": "SEM MUDANÇA DE STATUS",
        "ultimoStatus": "Anulação de sinistro",
    },
    "57": {
        "descricao": "Indenização Cancelada",
        "statusBadge": "SEM MUDANÇA DE STATUS",
        "ultimoStatus": "Indenização Cancelada",
    },
    "58": {
        "descricao": "Consolidação Cancelada",
        "statusBadge": "SEM MUDANÇA DE STATUS",
        "ultimoStatus": "Consolidação Cancelada",
    },
    "59": {
        "descricao": "Consolidação de Entregas",
        "statusBadge": "CONSOLIDADO",
        "ultimoStatus": "Consolidação de Entregas",
    },
    "60": {
        "descricao": "Processamento Realizado",
        "statusBadge": "PROCESSADO",
        "ultimoStatus": "Processamento Realizado",
    },
    "61": {
        "descricao": "Processamento Anulado",
        "statusBadge": "SEM MUDANÇA DE STATUS",
        "ultimoStatus": "Processamento Anulado",
    },
    "62": {
        "descricao": "Consolidação Realizada",
        "statusBadge": "CONSOLIDADO",
        "ultimoStatus": "Consolidação Realizada",
    },
    "63": {
        "descricao": "Consolidação Cancelada",
        "statusBadge": "SEM MUDANÇA DE STATUS",
        "ultimoStatus": "Consolidação Cancelada",
    },
    "64": {
        "descricao": "Envio de remessa cancelada para devolução",
        "statusBadge": "DEVOLUÇÃO",
        "ultimoStatus": "Envio de remessa cancelada para devolução",
    },
    "65": {
        "descricao": "Sinistro registrado na remessa",
        "statusBadge": "PENDENTE",
        "ultimoStatus": "Sinistro registrado na remessa",
    },
    "66": {
        "descricao": "CTe Emitido",
        "statusBadge": "SEM MUDANÇA DE STATUS",
        "ultimoStatus": "CTe Emitido",
    },
    "67": {
        "descricao": "CTe Cancelado",
        "statusBadge": "SEM MUDANÇA DE STATUS",
        "ultimoStatus": "CTe Cancelado",
    },
    "68": {
        "descricao": "Solicitação Transmitida",
        "statusBadge": "COLETADO",
        "ultimoStatus": "Solicitação Transmitida",
    },
    "69": {
        "descricao": "Produtos de entrega rejeitada separados para devolução",
        "statusBadge": "DEVOLUÇÃO",
        "ultimoStatus": "Produtos de entrega rejeitada separados para devolução",
    },
    "70": {
        "descricao": "Atribuição manual para outra empresa",
        "statusBadge": "ROTA ALTERADA",
        "ultimoStatus": "Atribuição manual para outra empresa",
    },
    "71": {
        "descricao": "Geração romaneio de consolidados",
        "statusBadge": "SEM MUDANÇA DE STATUS",
        "ultimoStatus": "Geração romaneio de consolidados",
    },
    "72": {
        "descricao": "Recebimento de volumes consolidados",
        "statusBadge": "RECEBIDO",
        "ultimoStatus": "Recebimento de volumes consolidados",
    },
    "73": {
        "descricao": "Insucesso ao receber consolidados",
        "statusBadge": "PENDENTE",
        "ultimoStatus": "Insucesso ao receber consolidados",
    },
    "74": {
        "descricao": "Cancelamento do Romaneio de Redespacho",
        "statusBadge": "SEM MUDANÇA DE STATUS",
        "ultimoStatus": "Cancelamento do Romaneio de Redespacho",
    },
    "75": {
        "descricao": "Transmissão de Cancelamento",
        "statusBadge": "SEM MUDANÇA DE STATUS",
        "ultimoStatus": "Transmissão de Cancelamento",
    },
    "76": {
        "descricao": "Carga não recebida",
        "statusBadge": "SEM MUDANÇA DE STATUS",
        "ultimoStatus": "Carga não recebida",
    },
    "77": {
        "descricao": "Objeto postado no agente de transporte",
        "statusBadge": "POSTADO",
        "ultimoStatus": "Objeto postado no agente de transporte",
    },
    "78": {
        "descricao": "Aguardando retirada no agente de transporte",
        "statusBadge": "AGUARDANDO RETIRADA",
        "ultimoStatus": "Aguardando retirada no agente de transporte",
    },
    "79": {
        "descricao": "Coleta Anulada",
        "statusBadge": "SEM MUDANÇA DE STATUS",
        "ultimoStatus": "Coleta Anulada",
    },
    "80": {
        "descricao": "Entrega Anulada",
        "statusBadge": "SEM MUDANÇA DE STATUS",
        "ultimoStatus": "Entrega Anulada",
    },
    "81": {
        "descricao": "Transferência Devolução Realizada",
        "statusBadge": "DEVOLVER",
        "ultimoStatus": "Transferência Devolução Realizada",
    },
    "82": {
        "descricao": "Solicitação Liberada para entrega",
        "statusBadge": "LIBERADO PARA ENTREGA",
        "ultimoStatus": "Solicitação Liberada para entrega",
    },
    "83": {
        "descricao": "Solicitação enviada para devolução",
        "statusBadge": "DEVOLUÇÃO",
        "ultimoStatus": "Solicitação enviada para devolução",
    },
    "84": {
        "descricao": "Anulação de Cancelamento",
        "statusBadge": "SEM MUDANÇA DE STATUS",
        "ultimoStatus": "Anulação de Cancelamento",
    },
    "85": {
        "descricao": "Carga alocada em Voô",
        "statusBadge": "SEM MUDANÇA DE STATUS",
        "ultimoStatus": "Carga alocada em Voô",
    },
    "86": {
        "descricao": "Embarque aéreo confirmado",
        "statusBadge": "SEM MUDANÇA DE STATUS",
        "ultimoStatus": "Embarque aéreo confirmado",
    },
    "87": {
        "descricao": "Carga desembarcada no aeroporto",
        "statusBadge": "SEM MUDANÇA DE STATUS",
        "ultimoStatus": "Carga desembarcada no aeroporto",
    },
    "88": {
        "descricao": "Aguardando desembarque aéreo",
        "statusBadge": "SEM MUDANÇA DE STATUS",
        "ultimoStatus": "Aguardando desembarque aéreo",
    },
    "89": {
        "descricao": "Aguardando embarque no aeroporto",
        "statusBadge": "SEM MUDANÇA DE STATUS",
        "ultimoStatus": "Aguardando embarque no aeroporto",
    },
    "90": {
        "descricao": "Carga não embarcada",
        "statusBadge": "SEM MUDANÇA DE STATUS",
        "ultimoStatus": "Carga não embarcada",
    },
    "91": {
        "descricao": "Carga em conexão aérea",
        "statusBadge": "SEM MUDANÇA DE STATUS",
        "ultimoStatus": "Carga em conexão aérea",
    },
    "92": {
        "descricao": "Prazo alterado manualmente",
        "statusBadge": "REAGENDADO",
        "ultimoStatus": "Prazo alterado manualmente",
    },
    "93": {
        "descricao": "Volume removido da consolidação",
        "statusBadge": "SEM MUDANÇA DE STATUS",
        "ultimoStatus": "Volume removido da consolidação",
    },
    "94": {
        "descricao": "Carga a ser devolvida na base do parceiro",
        "statusBadge": "DEVOLUÇÃO",
        "ultimoStatus": "Carga a ser devolvida na base do parceiro",
    },
    "95": {
        "descricao": "Parceiro com carga em trânsito para devolução",
        "statusBadge": "DEVOLUÇÃO",
        "ultimoStatus": "Parceiro com carga em trânsito para devolução",
    },
    "96": {
        "descricao": "Insucesso na transferência da devolução",
        "statusBadge": "PENDENTE",
        "ultimoStatus": "Insucesso na transferência da devolução",
    },
    "97": {
        "descricao": "Devolução realizada pelo parceiro",
        "statusBadge": "DEVOLVIDO",
        "ultimoStatus": "Devolução realizada pelo parceiro",
    },
    "98": {
        "descricao": "Carga Recebida",
        "statusBadge": "RECEBIDO",
        "ultimoStatus": "Carga Recebida",
    },
    "99": {
        "descricao": "Anulação de Recebimento",
        "statusBadge": "SEM MUDANÇA DE STATUS",
        "ultimoStatus": "Anulação de Recebimento",
    },
    "100": {
        "descricao": "Anulação de Processamento",
        "statusBadge": "SEM MUDANÇA DE STATUS",
        "ultimoStatus": "Anulação de Processamento",
    },
    "101": {
        "descricao": "Anulação de Consolidação",
        "statusBadge": "SEM MUDANÇA DE STATUS",
        "ultimoStatus": "Anulação de Consolidação",
    },
    "102": {
        "descricao": "Registro de perda de volumes consolidados",
        "statusBadge": "PENDENTE",
        "ultimoStatus": "Registro de perda de volumes consolidados",
    },
    "103": {
        "descricao": "Alteração de valor a receber na entrega",
        "statusBadge": "SEM MUDANÇA DE STATUS",
        "ultimoStatus": "Alteração de valor a receber na entrega",
    },
    "104": {
        "descricao": "Recebimento de volumes unidade operacional",
        "statusBadge": "RECEBIDO",
        "ultimoStatus": "Recebimento de volumes unidade operacional",
    },
    "105": {
        "descricao": "Liberado pela Fiscalização",
        "statusBadge": "PENDENTE",
        "ultimoStatus": "Liberado pela Fiscalização",
    },
    "106": {
        "descricao": "Transferencia de Consolidacao em Unidade Divergente",
        "statusBadge": "SEM MUDANÇA DE STATUS",
        "ultimoStatus": "Transferencia de Consolidacao em Unidade Divergente",
    },
    "107": {
        "descricao": "Desconsolidação de volumes",
        "statusBadge": "SEM MUDANÇA DE STATUS",
        "ultimoStatus": "Desconsolidação de volumes",
    },
    "108": {
        "descricao": "Recebimento do Volume para Devolução",
        "statusBadge": "DEVOLUÇÃO",
        "ultimoStatus": "Recebimento do Volume para Devolução",
    },
    "109": {
        "descricao": "Volume separado para rota",
        "statusBadge": "EM ROTA",
        "ultimoStatus": "Volume separado para rota",
    },
    "110": {
        "descricao": "Volume removido da pré rota",
        "statusBadge": "SEM MUDANÇA DE STATUS",
        "ultimoStatus": "Volume removido da pré rota",
    },
    "111": {
        "descricao": "Condutor em rota para coleta",
        "statusBadge": "EM ROTA",
        "ultimoStatus": "Condutor em rota para coleta",
    },
    "112": {
        "descricao": "Volumes transferido para parceiro de transporte",
        "statusBadge": "EM TRANSFERÊNCIA",
        "ultimoStatus": "Volumes transferido para parceiro de transporte",
    },
    "113": {
        "descricao": "Devolução estornada",
        "statusBadge": "SEM MUDANÇA DE STATUS",
        "ultimoStatus": "Devolução estornada",
    },
    "114": {
        "descricao": "Alteração de prazo cliente",
        "statusBadge": "REAGENDADO",
        "ultimoStatus": "Alteração de prazo cliente",
    },
    "115": {
        "descricao": "Em rota para o endereço do cliente",
        "statusBadge": "EM ROTA",
        "ultimoStatus": "Em rota para o endereço do cliente",
    },
}

DE_PARA_INSUCESSO = {
    "2": "Chuvas Torrenciais",
    "3": "Rua não Localizada",
    "4": "Número não Localizado",
    "7": "Desacordo com o pedido",
    "8": "Pessoa desconhecida",
    "9": "Mudança de endereço",
    "10": "Falecimento",
    "11": "Recusada pelo cliente",
    "16": "Endereço sem acesso",
    "18": "Produto avariado no transporte",
    "19": "Fatores naturais extremos",
    "20": "Pessoa em viagem",
    "24": "Retido na fiscalização",
    "28": "Problemas fiscais",
    "29": "Cep incorreto",
    "30": "Suspensa pelo destinatário",
    "32": "Feriado local",
    "33": "Pessoa não localizada no local",
    "34": "Estabelecimento/local fechado",
    "35": "Extravio",
    "36": "Furto/roubo",
    "44": "Endereço Insuficiente",
    "46": "Área de Risco",
    "56": "Cliente Ausente 2º Tentativa",
    "57": "Cliente Ausente 3º Tentativa",
    "63": "Item divergente",
    "71": "Embalagem incorreta",
    "72": "Estabelecimento reportou sinistro",
    "73": "Venda cancelada",
    "75": "Problemas no veículo",
    "81": "Tempo Insuficiente",
    "83": "Cliente Ausente 4° Tentativa",
    "84": "Cliente Ausente 5° Tentativa",
    "86": "Setup de remessa concluído",
    "1420": "Cliente Ausente 1° Tentativa",
    "1421": "CUSTÓDIA",
}